@startuml
!theme spacelab
title Écrire une info-lettre
|Admin|
start
:Se connecter à Wix Studio;
:Accéder au tableau de bord administrateur de Wix Studio;
:Accéder au panneau info-lettre;
:Créer une info-lettre:
|Wix Studio|
:Enregistrer l'info-lettre;
|Admin|
:Saisir le contenu de l'infolettre;
:Choisir les destinataires (tous les abonnés ou sélectionnés);
|Wix Studio|
:Prévisualiser l'infolettre;
:Vérifier les informations d'envoi (destinataires, contenu);
|Admin|
:Confirmer l'envoi de l'infolettre;
|Wix Studio|
:Envoyer l'infolettre à tous les abonnés ou sélectionnés;
stop
@enduml
