@startuml
!theme spacelab
title Créer un blogue
|Admin|
start
:Se connecter à Wix Studio;
:Accéder au tableau de bord administrateur de Wix Studio;
:Accéder à la section Blogue;
|Admin|
:Ajouter un blogue;
|Wix Studio|
:Enregistre un nouveau blogue;
|Admin|
:Saisir le contenu du nouvel article;
:Ajouter des images ou autres médias (optionnel);
:Choisir la catégorie ou les tags (optionnel);
|Wix Studio|
:Prévisualiser l'article;
|Admin|
:Confirmer la publication de l'article;
|Wix Studio|
:Publier l'article sur le blogue;
stop
@enduml
